### ISSUE TITLE
I have attempted to add an addon, and it acts like it's not recognizing it there at all.

### ISSUE THREAD

**Issue by btannen000** [Windower/Issues#1063]
I tried to install XivParty addon. I followed their instructions precisely: Put XivParty folder in addons. So, I did, there's the XivParty folder and all its contents in addons. It looks like any other addon. Looking in the folder, I see there IS an xivparty.lua -- So I open the game and open the windower interface. I type lua load Xivparty -- it tells me file does not exist.  I'm looking at the file myself! But that's all it does, I cannot figure out a solution as so what I've done wrong or what I can do to make XivParty work.

Anyone can you please help?

**Comment by RubenatorX** [comment]
This kind of problem feel free to come chat with us in discord. https://discord.gg/v6pk6uy (you can find this link at the top of windower.net)
This sort of problem in general happens when you have ended up with multiple setups of windower and you're editing files for a different one than you are running.

**Comment by RubenatorX** [comment]
Solved in discord. The addon folder name was `XivParty-master` instead of `XivParty`
<https://discordapp.com/channels/338590234235371531/338590234235371531/743501759422529567>
