### ISSUE TITLE
Windower crash if i have any addon load 

### ISSUE THREAD

**Issue by noswear922** [Windower/Issues#1084]
as the title says Windower crash my game if i have addon loaded. i am trying to use xivbar addon. I tried to reinstall the game and the program itself. I installed them on another ssd, I tried something, maybe I'm doing something wrong, so I'm looking for some help

**Comment by RubenatorX** [comment]
First, I'm confused. Can you not get __any__ addon to load? Or just struggling with xivbar? If any, what ones have you tried?
Furthermore, this generally happens when the addon is display text that is trying to load a font it can't find, and that problem happens significantly more often on private servers than on retail.
If that's your problem, then plenty of addons that don't display text on screen should work. Also, for those that are crashing, you can simply load them and crash, and then go edit that addon's particular settings file, and change the font to something simple like `Arial` and it solves the crash problem for that addon the next time you log in.
If you have trouble with this, feel free to come chat with us in the #support channel of Discord (invite link found at the top of windower.net)

**Comment by noswear922** [comment]
> First, I'm confused. Can you not get **any** addon to load? Or just struggling with xivbar? If any, what ones have you tried? Furthermore, this generally happens when the addon is display text that is trying to load a font it can't find, and that problem happens significantly more often on private servers than on retail. If that's your problem, then plenty of addons that don't display text on screen should work. Also, for those that are crashing, you can simply load them and crash, and then go edit that addon's particular settings file, and change the font to something simple like `Arial` and it solves the crash problem for that addon the next time you log in. If you have trouble with this, feel free to come chat with us in the #support channel of Discord (invite link found at the top of windower.net)

Hey, soo I did try to load the game no addons and plugins game work normally no problem.i Try like  5-6 addons and any of it crashes the game. yes, I'm on private server "Eden".

**Comment by noswear922** [comment]
Thank you so much yea the Font work now and it load normal thank you so much

**Comment by Byrth** [comment]
Looks like this is resolved!
