### ISSUE TITLE
Crash on FFXI Startup

### ISSUE THREAD

**Issue by garth39** [Windower/Issues#136]
OS:  Windows 8
Windower Version(s):  3.431, 3.432, and 4 (Beta)
Symtom:  Crash occurs during transition into character selection lobby

FFXI works without Windower

Crash symptoms the same regardless of Windower version used.  Windower was working on the Windows 8 installation prior to the FFXI March version update.

I can submit the Windows 8 WER Crash report, but the GIT site will not permit upload.  Is there an alternative means to deliver the report?

**Comment by Flanteus** [comment]
It's POL.
I didnt have any problem before until I had to run vanilla FFXI for a quest, and after that I was never able to run windower4 without 100% crash, I tried almost everything ever suggested here and in other sites, then before the last step (reinstalling windows) I did a system restore (using a point before running vanilla FFXI) and it was FIXED! now i can use windower again!

Now, I dont understand all this technical stuff but what I noticed is that POL window that appear for 1-2 seconds (that has ESBR notice) was BIGGER when windower was working, but with the crashing-POL that window was smaller for some reason, now it's back to normal size in fact I realized the problem was fixed before i even signed into POL because the size of that window, as if the "working-POL" is the one that windower4 loaded...

**Comment by pehass2** [comment]
This: 

"Flanteus commented on 27 May
It's POL.
I didnt have any problem before until I had to run vanilla FFXI for a quest, and after that I was never able to run windower4 without 100% crash, I tried almost everything ever suggested here and in other sites, then before the last step (reinstalling windows) I did a system restore (using a point before running vanilla FFXI) and it was FIXED! now i can use windower again!

Now, I dont understand all this technical stuff but what I noticed is that POL window that appear for 1-2 seconds (that has ESBR notice) was BIGGER when windower was working, but with the crashing-POL that window was smaller for some reason, now it's back to normal size in fact I realized the problem was fixed before i even signed into POL because the size of that window, as if the "working-POL" is the one that windower4 loaded..."

I have run Windower4 since release without an issue, ever. But a few days ago I was running a alt through ASA (A Shantotto Ascension: Mission 6 "Enemy of the empire II" AFTER the fight I clicked the rock again for a cs, my game froze and I have not been able to use Windower4 since. I have:

- un-installed and reinstalled FFXI - no dice, soon as game tries to launch I get the "Playonline encountered an error and needs to close"
- un-installed and reinstalled Graphics Drivers (Geoforce 660M - Asus ROG G75V Laptop)
- system restore back to 2 weeks prior - No dice
- Reinstalled Windows 8 (8.1) - reinstalled FFXI - reinstalled Windower4 - No dice
- Vanilla Worked(s) fine in all above cases
- Ashita2 works
- Every other game runs and works fine in all cases above...

I've been thinking about loading Win7 (maybe dual boot?), but does that guarantee Windower4 will work??

Anyone have any ideas?

**Comment by z16** [comment]
Pretty much, this error is Windows 8 exclusive from everything we can tell.

**Comment by braskasguardian** [comment]
I had the same access violation error code (Exception code: 0xc0000005) from Windows Event Viewer with my crash (On a Virtual Machine, Windows 10 x64 POL -> FFXI Startup crash) and **found that setting the resolution to 800x600 but more importatnly making sure that compatibility mode for both POL.EXE and Windower itself were disabled**. So it seems my crashes were related to using Windows 7 compatibility mode being turned on in the properties.

**Comment by Byrth** [comment]
Windower's next minor version update (v4.3) was released today on -dev. To try it out, duplicate your entire Windower directory, then download http://update.windower.net/dev/Windower.exe , replace your existing Windower.exe, and log in. I think there's a pretty good chance that it solves your problem, or at least changes it substantially. You can read more here: #876

I am going to close this now. Please let us know in that thread (and reference this thread) if you still have crash issues.

**Comment by Jbliske** [comment]
I assume this has never been fixed?  I just recently started playing FFXI again.  Downloaded Windower 4 and I get a CTD when FFXI loads (after the ESRB notice).  I'm running Windows7 Pro.  I have tried just about everything above without success.


Windows Event log
---

```
Faulting application name: pol.exe, version: 1.18.13.0, time stamp: 0x4e3bcddc
Faulting module name: Hook.dll, version: 4.3.2.1, time stamp: 0x5940a84a
Exception code: 0xc0000005
Fault offset: 0x0004b149
Faulting process id: 0x191c
Faulting application start time: 0x01d334d50b1a73e3
Faulting application path: C:\Program Files (x86)\Steam\steamapps\common\FFXINA\SquareEnix\PlayOnlineViewer\pol.exe
Faulting module path: C:\Program Files (x86)\Steam\steamapps\common\FFXINA\SquareEnix\FINAL FANTASY XI\Hook.dll
Report Id: 69282781-a0c8-11e7-b46e-54a050e650df
```
