### ISSUE TITLE
Windower 4 fails to launch. Blank white box.

### ISSUE THREAD

**Issue by DavionCA** [Windower/Issues#176]
Description: Windows 4 (fresh install) fails to load beyond a white, tall, narrow box. Initial "Windower 4" banner appears, then is replaced with the blank box. Common button locations (Close in top-right corner) seem to work.

OS: Windows 8 Enterprise x64

Windower Version: 4

Plug-ins/addons/other: Only what comes with the installer.

Settings.xml: 

```
<?xml version="1.0" encoding="utf-8"?>
<settings>
<profile name="">
<consolekey>Insert</consolekey>
<uiscale>1</uiscale>
</profile>
</settings>
```

Details of how the issue happened: This is after initial install of Windower 4. Windower 3 runs without issue. Tried turning things off (UAC, firewall, etc.) and used various Compatibility Mode options (7, XP SP3/2, etc.) with no difference. Launching with "Run as Administrator", but no difference. Hook.dll appears to be downloading upon launch. System has 2 GFX systems (Intel and Nvidia), tried forcing it to run on either with no change in results.

System is a Dell XPS L702X.

**Comment by sinni800** [comment]
I had this problem again now and doing DisableHWAcceleration (Registry) certainly works.

Windower will also probably never need any hardware acceleration, so why not disable it for windower at all?

in `OnSourceInitialized`

You can do this on your `window`:

`        var hwndSource = PresentationSource.FromVisual(this) as HwndSource;

        if (hwndSource != null)
            hwndSource.CompositionTarget.RenderMode = RenderMode.SoftwareOnly;`

Because you use Github but don't actually open source I can't show you where to put it. Heh.

**Comment by alphaONE2** [comment]
Yes, I'm aware of the `RenderMode` property. I did consider doing this long ago but it never happened for multiple reasons. Another solution is to set the Window background to Transparent and nest a UI element with an opaque background; this keeps HW acceleration, but turns off ClearType. You can partially turn ClearType back on on a case-by-case basis using `RenderOptions.ClearTypeHint`, but you have to sprinkle it all over the XAML.

The entire problem ultimately results from a trick used to enable the DWM drop shadow for a window with `WindowStyle="None"`. On some GPUs the window render target's alpha channel is garbage unless you explicitly force WPF to clear to transparent, and this messes up the DWM compositing.

Ultimately I decided to use a completely different method in Windower 5. The new method has the benefit of also restoring the minimize/restore animations and sidesteps the entire problem with the alpha channel, but I don't really want to back port the code to Windower 4.

If you really want to get this fixed in Windower 4, you might be able to talk @z16 into changing the `RenderMode`.

**Comment by z16** [comment]
> If you really want to get this fixed in Windower 4, you might be able to talk @z16 into changing the `RenderMode`.

You may not. I dread doing anything for v4 at this point, and with Windower 5 approaching some state of maturity I don't feel it's worth the effort.

**Comment by sinni800** [comment]
Well I would fork it if it was open source and put it in myself for now.
