### ISSUE TITLE
[Gamepad feature] block gamepad input when game window loses focus

### ISSUE THREAD

**Issue by Zireael** [Windower/Issues#382]
Hi, would it be possible to block gamepad window when game window loses focus?
My friend wants to use gamepad in FFXIV whilst waiting in FFXI for event start, but it seems the gamepad input goes into FFXIV and to FFXI even if FFXI window is minimized.
Thanks in advance!

**Comment by mrphain** [comment]
I'm a FF14 player looking to explore the world of Vana'diel, but I have one huge problem. When FF11 (using windower) is minimized or out of focus the gamepad (Xbox 360 USB Microsoft drivers) continues to operate FF11! This is awful. It makes trying to simultaneously play FF11 and FF14 really miserable because I use my gamepad for both games.

SOLUTION:
Create a toggle to block/enable gamepad input to the FF11 window when out of focus/minimized.

PLEASE HELP
Thank you

**Comment by z16** [comment]
A kinda dumb workaround until I get to adding a toggle for it is to start a second FFXI instance. It will not behave this way when two FFXI instances are detected. You will, however, need a second POL account to do it.

I will try to get to it by the next weekend, unfortunately I'm really busy until then.

**Comment by cairface** [comment]
Seems I fixed this. Better late than never.
