### ISSUE TITLE
Windower crashes after zoning to incursion

### ISSUE THREAD

**Issue by Diosax** [Windower/Issues#609]
My windower crashes after zoning to incursion

**Comment by Nifim** [comment]
new link to windower forum post arcon linked: https://forums.windower.net/index.php@sharelink=download%3BaHR0cDovL2ZvcnVtcy53aW5kb3dlci5uZXQvaW5kZXgucGhwPy90b3BpYy82NTctZ2FtZS1jcmFzaC1vbi16b25lLWNoYW5nZS9wYWdlLTM,%3BZ2FtZSBjcmFzaCBvbiB6b25lIGNoYW5nZQ,,.html

No resolution came in that discussion, the issue could be assumed to be fixed by the reinstall they said they would attempt on their last post.
