### ISSUE TITLE
draw distance no longer works

### ISSUE THREAD

**Issue by charliet26** [Windower/Issues#675]
hi I have been using the drawdistance plugin for a long time now and its always worked fine, since the January version update it has stopped working, I can load it manually on my pc but on my laptop it says the file does not exist, I have reinstalled the file and it makes no difference, it still loads with the shows up on the console but pressing alt f10 no longer extends the range.

**Comment by Byrth** [comment]
It has been replaced by the Config plugin. Config is a combination of multiple single feature plugins, so that fewer plugins need to be recompiled each update and we can get everyone back up and running even faster.

Sorry for the confusion. I am going to close this issue now. Please let us know if you cannot get config to work for you.
