### ISSUE TITLE
Cant reload gearswap

### ISSUE THREAD

**Issue by Diosax** [Windower/Issues#742]
//lua u gearswap
//lua l gearswap

not working

**Comment by Byrth** [comment]
GearSwap was stubbed off for a while and unloaded itself on load in order to prevent people from sending bad packets. Try rerunning launcher. If that doesn't work:
1) Download the zip from here (right side of page): https://github.com/Windower/Lua
2) Unzip it
3) Merge the addons folder with your windower/addons folder
4) Reload GearSwap

Because this was very likely due to the stubbed version, I'm going to close it now. Please feel free to reopen it or make a new issue if this does not work for you.
