### ISSUE TITLE
GearSwap failing to change gear after disconnecting.

### ISSUE THREAD

**Issue by infernoboy** [Windower/Issues#777]
I disconnected form the game during a SR while attempting to select a spell from the menu and when I came back on, GearSwap would no longer change my gear. I changed to different jobs and none of them would work. GearSwap shows that it is loading the file and I can run the custom "job_self_commands". Running "gs equip naked" does remove my gear, but, e.g., "gs equip midcast.Cure" does not; it does not show any type of error. Switching on debugmode shows that all the gear is being found and is correct for what I am casting. I deleted the GearSwap folder and re-downloaded it, but the issue remains.

P.S. Every time I /shutdown from the game and it reaches 0, it crashes instead of quitting successfully. The same thing happens if I /logout and then click "Back". I don't know if logging out without crashing would fix it since I can't.

**Comment by nitrous24** [comment]
the only way to fix the crashing immediately when you /shutdown or logout/back is to unload everything. Some plugins do not take kindly to the game trying to exit.  As for the other thing i can't help sorry

**Comment by Byrth** [comment]
I'm pretty sure you downloaded a new hook when you logged back in and it caused this issue. The job level table was shifted, so GearSwap was detecting that your level is too low to wear your currently equipped gear. That's why it would unequip gear but not equip gear.

It should be fixed by now, because we put out a fixed hook, so I'm closing the issue.
