### ISSUE TITLE
Targets not showing up

### ISSUE THREAD

**Issue by Y2HBK** [Windower/Issues#799]
So Ive had this happen twice now. Im running the steam version of FFXI and using the latest build of Windower 4 on Windows 10. 

Once I was looking for a portal to target. Knew exactly where it should be and it wasnt there. I logged out and back in and boom it was there. 

Tonight I was doing Yorcia Weald Alluvion Skirmish and as soon as I entered the butterfly target thing was visible but I couldnt target it. I had to log out and back in then it became targetable. The book didnt show up, either but did after I logged.

**Comment by Byrth** [comment]
This is not a windower issue.

SE's servers sometimes don't send you the packet to spawn NPCs. It happens to me frequently in the new zone (Reisenjima?) and feels more frequent when there are a lot of players around.

Anyway, because it's purely a SE server-side issue, there's nothing we can do to fix it and I'm going to close the issue.

**Comment by z16** [comment]
For the record, you don't usually need to relog, running out of range then back in is usually sufficient. I.e. run more than 50 yalms away from where it is supposed to spawn, then run back in, that will (or should) make the server send a new packet.
