### ISSUE TITLE
LuaCore - get_mob_by_id(19000000) reliably causes a crash

### ISSUE THREAD

**Issue by Byrth** [Windower/Issues#803]
I can't really even begin to guess why. get_mob_by_id should just iterate over the mob array and compare ID values. 19mil is a lot, but it's well below the maximum value for an unsigned INT.

get_mob_by_id(190000) (190k) does not cause a crash
get_mob_by_id(1900000) (1.9 mil) does not cause a crash
get_mob_by_id(18000000) (18 mil) does not cause a crash.
get_mob_by_id(18999999) (19 mil -1) does cause a crash.
get_mob_by_id(19000000) (19 mil) does cause a crash.

So somewhere between 18 and 19 mil it starts crashing.

**Comment by alphaONE2** [comment]
get_mob_by_id takes a shortcut for NPC IDs (where the top 8 bits are not 0). It simply extracts the mob index from the low 12 bits, and then looks up the mob at that index. 19000000 has a 1 in the top 8 bits, so it's considered an NPC ID, and the low 12 bits have the value 2752, which is beyond the end of the mob array. Interestingly 18000000 is an NPC ID with an index of 2176, which is also out of range.

So, why does 19000000 fail while 18000000 works? I suspect you just got lucky. We check the validity of a mob array index by checking if the pointer in the specified slot is null. So if the memory being read happens to have a 0 then nothing bad happens, otherwise we end up reading back a pointer to a random memory location, which may or may not be valid. If it's valid the table return with have garbage data, if it's not you get an access violation.

Looks like we need to do some extra validation on NPC IDs. At the very least we should verify that `index < 2048`.

**Comment by Byrth** [comment]
I am not sure why this is fixed but not closed, so I'm going to close it.

**Comment by z16** [comment]
I don't know either!
