### ISSUE TITLE
Can't Multibox

### ISSUE THREAD

**Issue by Hiep1882** [Windower/Issues#809]
I'm currently multiboxing (2-5 chars) and periodically my display driver keeps failing and resetting itself, resulting in my game to crash. Any ideas?

**Comment by z16** [comment]
Are you on Windows 10? I've been experiencing the same issue ever since I switched to Windows 10, but it is not FFXI specific. It happens occasionally, seemingly randomly, even when not in the game.

**Comment by Byrth** [comment]
This problem can occur for both hardware and software reasons.
* If you're using a laptop, it might be overheating.
* If you're using a newish AMD card, it's likely something to do with their drivers/hardware

Either way, it's probably not being caused by Windower and I'm sure you solved it in the last year anyway, so I'm going to close this issue.
