### ISSUE TITLE
Sandbox plugin causes windower to crash on load.

### ISSUE THREAD

**Issue by Genesis-Legion** [Windower/Issues#831]
After doing some looking around and trying to alleviate the dualbox chat log issues I came across the sandbox plugin, but whenever windower attempts to load the plugin windower instantly crashes.

Here's a crash dump if I did it correctly.
https://onedrive.live.com/redir?resid=822760EF3543ED8E!682&authkey=!ANReUizGGVsYhlY&ithint=file%2cdmp

**Comment by Genesis-Legion** [comment]
Get this in windbg when loading sandbox 
`ModLoad: 00000000`06fb0000 00000000`06fd8000   C:\Program Files (x86)\Windower4\plugins\sandbox.DLL
(1384.808): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
KERNEL32!RegKrnInitialize+0x16:
757c59d6 3935b8028975    cmp     dword ptr [KERNEL32!g_RegKrnGlobalState+0xa0 (758902b8)],esi ds:002b:758902b8=00000000
`

**Comment by Byrth** [comment]
Are you running Windower with administrator rights?

**Comment by valient85** [comment]
I know this issue is a year old with no follow-up.  In troubleshooting a different issue I had turned on a windows feature called "Data Execution and Prevention" for all programs but added POL.EXE and wondower.exe as exceptions.  However, once sandbox loaded it caused an immediate crash.  Setting it back to DEP for essential windows programs resolved the crash for me.

**Comment by Byrth** [comment]
Thanks for clearing that up. That makes sense as a cause.

Sandbox changes the directory being read from / written to for different characters, so it probably triggered the DEP protection because it was altering a write address. I would not have guessed this as a cause because I would have thought turning DEP on for Windower would kill hook.dll and Sandbox would never have had a chance to load.

**Comment by alphaONE2** [comment]
@Byrth: Hook uses VirualProtectEx to modify the page's Read/Write/Execute permissions before doing any modifications. I'm guessing Sandbox isn't doing this.
