### ISSUE TITLE
July resources update is not being installed by Windower

### ISSUE THREAD

**Issue by Subadai** [Windower/Issues#844]
Windows 7 Pro, Windower live or dev branch. Resources were updated 2 days ago, but neither of my Windower installs are pulling them down. Any way to force Windower to update?

**Comment by alphaONE2** [comment]
This isn't really the right place for support questions, but you can download the resources manually from http://resources.windower.net/live/lua/ or http://resources.windower.net/dev/lua/ (these are exactly the same locations Windower downloads them from). Neither source appears to have been updated since June 7th.

**Comment by Subadai** [comment]
The version here on Github appears to be up-to-date: https://github.com/Windower/Resources/tree/master/lua. Someone should copy that to the windower.net location so that people's clients will update automatically.

**Comment by z16** [comment]
The resources were not updated yet. I'll do it today, along with some other fixes.

The Windower launcher does not pull the resources from GitHub but from our copies on our own server. We have them updated on GitHub (thanks to @KenshiDRK who submitted a pull request), but did not copy them to our server yet. After that they should be downloaded.

**Comment by z16** [comment]
Should be updated.
