### ISSUE TITLE
Windower v4.2 Hook/Launcher problems with Windows 8, 8.1, and 10

### ISSUE THREAD

**Issue by Byrth** [Windower/Issues#877]
I am opening this issue to condense all the other reports. If you are receiving a notification that I referenced/closed your issue, please run Windower's Launcher and see if version 4.3 resolves your issue.

**Crashes at the POL -> FFXI Transition:**
#835 : Pretty boilerplate, but has a comment regarding "Can only be displayed properly in 32 bit true color. Start Playonline Viewer anyway" might be helpful to people.
#802 : White screen on the transition from POL to FFXI.
#753 : Unclear which transition this report is referencing. Also contains an account of the "Breaking the Ice" CS that used to cause crashes.
#136 : The original thread dealing with this issue on Windows 8

**Crashes at the Launcher -> POL Transition:**
#836 : Graphical issues with Launcher as well as a crash.
#823 : Image of crashed POL with the message.
#822 : crash.log dump, seems like a different problem than the others.
#815 : Log of crash
#858 / #816 : Very little information to work with.

**Other (might be resolved by v4.3, but I'm not closing them because they seem so different):**
#814 : Crash when the guy plugs in his x-box 1 controller, potential peripherals problem
#761 : Windower crashes... twice

**Comment by KitF** [comment]
#136 is happening to me on the latest -dev build.

**Comment by Kincard** [comment]
Just posting to say that my issue in #805 does not occur anymore in 4.3. However it does not allow me to control the game with a gamepad while the window is out of focus. Not sure if this is an intentional change, but probably a bigger issue is that the window will start spamming button(s) when out of focus.

Thanks!

**Comment by z16** [comment]
@Kincard This is now determined by the setting in the FFXI config tool. Change it there.

**Comment by kuroganashi** [comment]
Hook Issues (4/27/2017)

**Comment by kuroganashi** [comment]
Game has unusual Crashes with new version Hook 4.3.0.6
Where 4.3.0.5 has it fully working.

**Comment by alphaONE2** [comment]
> Game has unusual Crashes with new version Hook 4.3.0.6
> Where 4.3.0.5 has it fully working.

This really isn't possible, 4.3.0.6 removed two lines of code compared to 4.3.0.5.

**Comment by cprivite** [comment]
> This really isn't possible, 4.3.0.6 removed two lines of code compared to 4.3.0.5.

You realize these are usually famous last words from programmers, right?

**Comment by z16** [comment]
Please do us a favor and provide us with a [crash dump](https://github.com/Windower/Issues/wiki/Enabling-automatic-crash-dumps). Just saying it's crashing doesn't help us. At the very least try to provide us at least with some more information about how/when it's crashing, otherwise we can't do anything. It's obviously not crashing for us or we wouldn't have pushed the update, so it's not something we can fix on our own, because we don't have anything to fix for us.

**Comment by Nifim** [comment]
All the linked issue are now closed, closing this one as well.
