### ISSUE TITLE
Windows key not captured with hook 4.3.0.5

### ISSUE THREAD

**Issue by radectheblm** [Windower/Issues#883]
After today's update to hook 4.3.0.5, any binds that include a windows key in them are not working if there is a command in windows that uses the same key combination.

@1 launches first program on taskbar
@x opens power user menu
@ by itself opens start menu

**Comment by fabianoffxi** [comment]
same for me . any info how to get around it . i have like 4 friends with the same issue

**Comment by Stratusx** [comment]
there has been resent issue's with the most recent update.
please include as much info as you can including general system you use (Since all windowers systems seems to be functioning differently atm, and include if you have the windowers 10 creators edition and if your using a XiLoader)
-Conditions that lead to the problem (Was it just the update or was it a sudden thing while you were playing then never stoped? etc),
-Your windower version/hook for both the normal and dev versions for fabuanoffxi
-and any dump reports that may have arisen as a resulted.

If it is because of the recent update, a suggestion from Byrth is to system restore to before the update that caused this problem, then disable/turn off your internet, (with the internet disabled the windower won't auto update)
load windower (Including w/e plugins/addons you need without any updates on them) then continue to playonline sign in screen, at this point you reconnect/enable your internet and it should hopefully work depending on if you restored to before the update. tuesday 25 april or ealier should be early enough for for normal windower.

This is only a temp fix until the general problems have been resolved

**Comment by alphaONE2** [comment]
The fix for this is relatively simple, but I'm not sure how long it will take me to get to it. I have some other higher priority issues to fix first.

**Comment by cairface** [comment]
This should be fixed as of hook 4.3.1.0, currently on the dev branch. Let me know if there are any issues. Thanks!
