### ISSUE TITLE
Windower Alt+Tabbing issue

### ISSUE THREAD

**Issue by oleboy17** [Windower/Issues#891]
Having a major multiboxing problem with windower. Everytime I alt+tab back and forth the Alt macro palette comes up and it is causing me to botch everything up. It has really thrown a wrench in my setup. Please help

**Comment by Aezaeo** [comment]
I too am having a similar issue, if not the same. I am only playing one character though. Whenever I Alt+Tab, from XI to any other window outside of the game, the alt macro palette remains active within XI until I tab back to the game.

So basically when Alt+Tabbing from the game to a different window, it seems like the alt key is becomes locked as if held down even though the game isn't the active window.

If you'd like any more information, let me know.

**Comment by vertos0** [comment]
Having the same issue, but it will always keep last key used pressed down. Spams it like until going back to that window and pressing the same key again. But then leave window and again last key used would be spammed. 

Honestly can't do anything currently because of it.


If you need any more info happy to help.

**Comment by Aezaeo** [comment]
I am on Windows 10 Home x64 version 1607 and do not have the creator's update.

It seems the problem started with the release of the 4.3 hook for me. I had never had anything similar happen to me prior to 4.3 hook. Also I am running the public version, haven't touched the -dev version. I haven't had the need. As for plugins that might interfere, hard to tell since everything was working prior to the 4.3 hook, and that's not to say that my game isn't working. 

This is more of annoyance than an actual problem. But since this wasn't happening prior to 4.3 i thought i'd let you guys know about it since 4.3 seems to have changed a few things.

**Comment by cairface** [comment]
This has been addressed as of hook 4.3.0.7, currently on the dev branch. I'm going to close this.
