### ISSUE TITLE
FFXI Crashing When Minimized

### ISSUE THREAD

**Issue by Taihaku347** [Windower/Issues#893]
Hello. I am running FFXI in windowed mode using Windower. My issue is that whenever I minimize the game and try to reopen it, the game crashes completely. When I run the game just in POL minimizing and reopening the game does not cause a crash. This happens on both the normal and developer versions of windower and I have no plugins or addons enabled. I was wondering if I could get some advice?

**Comment by Stratusx** [comment]
there has been resent issue's with the most recent update.
please include as much info as you can including general system you use (Since all windowers systems seems to be functioning differently atm, and include if you have the windowers 10 creators edition and if your using a XiLoader)
-Conditions that lead to the problem (Was it just the update or was it a sudden thing while you were playing then never stoped? etc),
-Your windower version/hook for both the normal and dev versions
-and any dump reports that may have arisen as a resulted.

If it is because of the recent update, a suggestion from Byrth is to system restore to before the update that caused this problem, then disable/turn off your internet, (with the internet disabled the windower won't auto update)
load windower (Including w/e plugins/addons you need without any updates on them) then continue to playonline sign in screen, at this point you reconnect/enable your internet and it should hopefully work depending on if you restored to before the update. tuesday 25 april  or ealier should be early enough for for normal windower.

This is only a temp fix until the general problems have been resolved

**Comment by cairface** [comment]
Is this still happening? We can't fix anything without a crash dump. Let us know, and provide one if so. Thanks!
