### ISSUE TITLE
Macro palette being wiped

### ISSUE THREAD

**Issue by firedemon2600** [Windower/Issues#898]
I've noticed that after changing jobs, then changing back, my macros have been wiped.  After reloading and older version of my settings and fixing them up again, the same thing would happen.  For example if I was on BLU and switched to PLD, and back to BLU, I would no longer have the BLU macro palette.  I did notice that MacroChanger was acting up and putting me on a random palette instead of the one I assigned, so I disabled the Addon and all seems to be fixed.

Windower version: 4.3
Addon: MacroChanger
OS: Windows 8

**Comment by Byrth** [comment]
macrochanger pretty much can't be responsible for this. It just inputs /macro book and /macro page commands.

Are you using anything that might interact with your macro files?

**Comment by firedemon2600** [comment]
I'm not using anything else that deals with macros.  It was acting up, like if I have my PLD set to change to 2-1, and I changed jobs, it would put me on a random palette like 1-8.  So I would manually switch it to 2-1, then if I changed jobs again, there was a chance it wasn't even switching my macro book at all.  Just seemed like every job I changed to then changed out of, my macros were wiped.

I saw that Omnys reported that he knew of a couple people with the same issue a well.  Since MacroChanger was acting up for me, I disabled it in-game after I reloaded my macros again and I've been fine for a day and a half now.

**Comment by Byrth** [comment]
Hm. This is very strange.

The only strange thing about the addon is that it uses the io library directly to interact with files, but that might just be a sign that it was released before the files library.

I refactored it substantially and pushed it to -dev, but honestly nothing should have changed.

**Comment by Aezaeo** [comment]
I too had this happen to me last night. It literally just happened out of nowhere. I was testing my SCH skillchain macros, when I went to burst off of the skillchain, I noticed a whole role from my palette was wiped clean, both the ALT and CTRL rows.

I reloaded my macros saved to the server to fix the issue, didn't want to bother writing them all out again. Since reloading my macros, the issue hasn't reoccurred for me. I'd also like to state that I too use MacroChanger, i.e. I still have MacroChanger loaded and the issue hasn't shown itself again. That's not to say that it isn't the culprit but @firedemon2600 said his issues stopped when unloading MacroChanger and my issues stopped and I still have MacroChanger loaded.

I'm on Windows 10 Home x64 version 1607. This issue occurred after the 4.3 hook update. I use the public version not the -dev.

**Comment by Selindrile** [comment]
I had a macro page dissapear on me as well, I am not using that addon.

**Comment by firedemon2600** [comment]
Was able to replicate the macros wiping upon loading MacroChanger so I'm 100% sure that's the cause.

**Comment by Byrth** [comment]
Hm. All macrochanger does is:
```windower.send_command('input /macro book '..book..';input /macro page '..page..';')```

The addon might be enabling whatever bug you're experiencing to occur more often (somehow), but because it's just invoking FFXI's normal functions I think it'd unlikely that it's the root cause.

**Comment by Byrth** [comment]
Do you guys also use commands like:
```windower,send_command('input /macro page '..page)```

in your GearSwap files?

I loaded -dev's macrochanger and spammed around in the job menu for a few minutes. Nothing was blanked, as far as I can tell.

**Comment by firedemon2600** [comment]
I don't use gearswap so it can't be that.  Tried it again and there doesn't seem to be a pattern to what it wipes.  I changed some jobs back and forth and 2 of the jobs that I didn't switch to were wiped upon inspection.  I'm really not sure what else to tell you, I don't use a lot of addons/plugins either, here's the list:
distance/guildwork/lightluggage/timers/tparty/azuresets/autoinvite/scoreboard/timestamp, and the disabled macrochanger.

**Comment by Byrth** [comment]
Okay, so just swapping jobs with those plugins/addons loaded causes you to lose entire macro books?

As an aside, I'd recommend using the addon version of Distance and replacing LightLuggage with Treasury.

**Comment by firedemon2600** [comment]
Yessir, that's all I run.  I do use the addon of Distance, and I'll check out Treasury.

**Comment by Byrth** [comment]
I added a short delay between the /macro book and /macro set command on -dev. Mind trying it?

Here is a link: https://www.dropbox.com/s/dms5gllr7i65nsc/macrochanger.lua?dl=0

**Comment by firedemon2600** [comment]
Looks like that fixed it Byrth, you rock, thanks.  I spammed changing jobs and nothing was wiped.

**Comment by Byrth** [comment]
Okay, so there's probably an issue with putting /macro book and /macro set into the outgoing text buffer with no delay between them. Do the rest of you use /macro book and /macro set without a delay in your gearswap files or whatever?

For some reason, in my gearswap files I always had wait statements between the two commands, but it was to solve this problem. I'm just confused about why this problem would arise now. >:-/

**Comment by Aezaeo** [comment]
I don't see any delays in my gearswap files in regards to /macro book/set. But again, as I stated in my post, my palette being wiped occurred out in the field. I wasn't constantly changing jobs to force the issue. So, my macro book/set had been set for sometime.

Here's whats in my luas:

function select_default_macro_book()
    -- Default macro set/book
    if player.sub_job == 'DNC' then
        set_macro_page(1, 2)
    else
        set_macro_page(1, 2)
    end
end

**Comment by Byrth** [comment]
Drat. That function (set_macro_page) from Motenten's lib actually does use a ```wait 0.1;```

Is there anything particular that you do out in the field, like swap macro sets again?

**Comment by Aezaeo** [comment]
>Is there anything particular that you do out in the field, like swap macro sets again?

@Byrth I did nothing particular at all. I wasn't messing with gearswap or addons/plugins at all. I was out in the field testing macros I made. I went out and tried to recreate the issue just now and could not replicate it. I've yet to re-encounter this issue, I've been fine since the day I reloaded my macros.

If you want me to test anything, just let me know.

**Comment by Selindrile** [comment]
@Byrth Yes I use those things in my gearswap and I believe that's what triggered my loss.

**Comment by Byrth** [comment]
Has anyone had this happen in the last 3 days?

**Comment by 6969696969696969** [comment]
I changed my subjob one night a few nights ago from dnc to nin & lost my bst macros.

"I reloaded my macros saved to the server to fix the issue, didn't want to bother writing them all out again. Since reloading my macros, the issue hasn't reoccurred for me."

This is exactly how it has been for me.  I reloaded a backup and haven't lost anything since.  I do use macrochanger.

It has been at least 4 or 5 days since this happened.

**Comment by Selindrile** [comment]
I haven't had this happen except for the one time.

**Comment by Byrth** [comment]
Hmm.... I'll leave it open and check back in a week. It still hasn't happened to me.

**Comment by firedemon2600** [comment]
Not since you changed it.  I am having another issue with crashing with macros, but I don't think it's related.  I posted a dump on FFXIAH.
