### ISSUE TITLE
Windower Crashing While Launching PlayOnline

### ISSUE THREAD

**Issue by happymanny** [Windower/Issues#901]
Hello

I just tried launching windower and after an update it crashes every time I try to launch at the  "Launching PlayOnline" screen.  I have tried the standard, dev, and an experimental build of windower from this post : https://github.com/Windower/Issues/issues/889#issuecomment-298811093

I also reinstalled playonline viewer.  Playonline viewer does launch by itself without windower.

![crash](https://cloud.githubusercontent.com/assets/28333832/25648648/2dae6b2c-2f9c-11e7-8458-3aaa3b6e1d75.png)

I do not get a crashdump, but I get this in crash.log:

`````````````````````````````````````````````````````````````````````
[ 4.3.6331.38835 ] 2017-05-03 04:55:13.9751768 UTC
---------------------------------------------------------------------
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Launcher.PlayOnlineLauncher.Launch(String hook, Profile profile, Boolean debug, TimeSpan timeout)
   at Launcher.Tasks.LaunchTask.Run()
   at Launcher.Tasks.Task.Run(Core core)
   at Launcher.Core.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
`````````````````````````````````````````````````````````````````````

Can anyone help?

**Comment by Stratusx** [comment]
currently certain PCs are having problems with loading playonline via windower, however playonline's original (Without windower) still works, if you already had windower installed prior to the new hook being updated, go to system restore, Start->all programs->accessories->system tools->->system restore
Restore your computer to a previous date that had the previous hook, then after your computer restarts/unplug/disable/turn off your internet,load windower and the auto update won't activate because theres no internet. load as many screens that you need to run your charactors until you reach the playonline sign in screen. then reconnect your internet and you'll be good.

This method is a temp fix as suggested by byrth so please be patient until the problem is found and updated

**Comment by alphaONE2** [comment]
This specific InvalidOperationException happens when you have your profile configured to auto-detect your client region, but launcher wasn't able to locate any installed copies of Final Fantasy XI. This part of launcher was not modified at all from 4.2. Did you just reinstall, by any chance? If you're using the Steam version you need to run the client once from Steam to initialize the registry.

@Stratusx: Could you please stop posting this to every issue? You're spamming everyone's inbox. Byrth also specifically said that if you do this, you are on your own. We don't recommend or support any configuration that disables auto-updates.

**Comment by Stratusx** [comment]
Roger, my apologise, won't happen again

**Comment by Sinnersslayer** [comment]
Hi guys,
Anyone can help me with Windower crashing while attempting to load POL?
I'm in WIndows 10 x64 running FF from the official web site (non-Steam)
Just noticed the crash.log file in windower folder.
Here what's inside.
Hope that help.
[crash.log](https://github.com/Windower/Issues/files/1765816/crash.log)

**Comment by Nifim** [comment]
This reminds me of the classic nasomi install braking retail, and would appear to fall under the "this would be better suited as a support chat on discord now"
