### ISSUE TITLE
Setkey problem

### ISSUE THREAD

**Issue by Byrth** [Windower/Issues#927]
Using setkey in a window that isn't in focus (for instance, ```send name setkey button down;wait 0.1;setkey button up```) may (or may not) work, but then when the window is back in focus you will be unable to use setkey on that button (as if its state is constantly set to up).

YMMV about the particular manifestation of this bug, but it's related to keys being set when the window is out of focus.

**Comment by Schliematt** [comment]
Ok i think i opened this in the lua area by mistake so ill just copy it here:

I talked to Radec on bg forums and this doesnt happen to him, but it happens to me. I am updated and on live version (doesnt work on dev either for me so) on Win10 Creators Update.

I am a dual boxer. Setkey works on the window that is in focus. But it does not work if the window is in the background and not in focus. I use setkey home when I zone on both characters so the camera is behind me and i will less likely zone back where i just came from accidently. But more importantly I use numpad7 to stop my mule from following. If i put the mule on follow and then use the SEND addon to setkey numpad7 down and then up, mule keeps following. If i switch afterward over to mule's window though, you suddenly see "follow cancelled." in the chat log. Same with the home key after zoning. ill zone on both characters. The next time i switch to the mule in background (within a short period of time) it will then center the camera behind the character (only after i switch to the mule's window).

To further test this I go to an open area and put mule in first person camera. I put his back to a wall. I switch to my main character and do "//send @Others setkey numpad8 down" (this normally moves you forward).
The mule does not move. I switch to the mule's window and he starts running forward. I switch back to the main's window and the mule stops moving. I switch to the mule and he starts running again.

So the setkey from send does work, but only triggers when the background window comes to focus. and stops when not in focus (despite the setkey is still set to down). and reactivates when that window becomes in focus again.

I have tried Always Enable Gamepad on and off and that doesnt change it. So I dunno what the issue is.

**Comment by Schliematt** [comment]
Just got back from a long road trip! But I tried something tonight. I unloaded all plugins and addons. and then loaded shortcuts gearswap and send. With Just those three loaded setkey worked fine with the mule. So now I will need to figure out which addon/plugin is fuckin it up. But I am sleepies so I will have to test this later.

**Comment by Schliematt** [comment]
OK so apparently chatmon is preventing me from using 
//send @others setkey numpad8 down

with chatmon loaded it prevents the setkey from working until you switch focus to the background character, in which it then activates.
