### ISSUE TITLE
Windower crashing on POL startup, Region not selectbale

### ISSUE THREAD

**Issue by Blex64** [Windower/Issues#985]
So my Windower has been crashing on an attempt to launch any profile. The crash log is showing this error:

System.InvalidOperationException: Operation is not valid due to the current state of the object.

From my understanding, this is caused by the Region being set to auto-select. However, there are no other options available to select in the profile editor. Making this even more frustrating is that I could have sworn it _was_ selectable the first time I checked today. Is this some kind of known issue? Or any known fix?

**Comment by alphaONE2** [comment]
Um, if there is no region available to select then it means the Launcher wasn't able to locate any installed copies of PlayOnline Viewer or Final Fantasy XI on your system. Do you have the Steam version of the game? If so, you need to launch PlayOnline Viewer directly from Steam (without Windower) at least once. Otherwise, the registry keys required for PlayOnline Viewer and Final Fantasy XI, won't be properly initialized.

**Comment by Blex64** [comment]
Hmm. It's not the Steam version, here's my registry and my install path:

https://imgur.com/a/uB9Tr

I see I don't have an install path there for FFXI, but the POL one looks fine?

**Comment by z16** [comment]
But you did install correctly and can launch it fine normally? Maybe do a reinstall to be sure... alternatively maybe add the missing key yourself.

Alternatively alternatively.... maybe it will even work if you specify the region and executable explicitly with `--executable=path/to/exe`, but I'm not entirely sure if this will work. Worth a try maybe.

**Comment by Blex64** [comment]
I can launch regular POL Viewer fine. I don't know about the game itself - I don't have a sub currently. 

I've reinstalled windower several times. I guess I could try reinstalling POL viewer?

**Comment by z16** [comment]
Did you actually install FFXI? Or just POL? I don't even know if it's possible to just install one, but that would certainly explain all this behavior. But yes, you can try reinstalling, so long as you make sure you install FFXI as well.

How do you expect to play without a FFXI sub? On a private server? If so, you will need to specify the executable regardless, since it shouldn't look into your POL folder (although xiloader might). Or are you on that one private server where they use a customized `pol.exe`?

**Comment by Blex64** [comment]
I had FFXI installed as well, yeah. I ended up just blowing everything up and reinstalling and it worked. No idea where it went wrong, but this is fixed.

**Comment by Nifim** [comment]
Clean install resolved issue.
