### ISSUE TITLE
Random Crash upon /logout while in Mog House

### ISSUE THREAD

**Issue by Iminiillusions** [Windower/Issues#990]
Crashing upon /logout in mog house. crash dump contained in the attached zip file.
[pol.exe.13652.zip](https://github.com/Windower/Issues/files/1901139/pol.exe.13652.zip)

**Comment by Nekseus** [comment]
Not sure if your still experiencing crashes but(though I'm not positive) it seems obvious to me the issue is with the JAwait plugin you have installed. The incoming field causing you to crash is "Repositioning." Try playing without it for awhile.

To edit the plugins that load make sure they are not included at the top of your launcher settings file(settings.xml in the root folder) in addition to the init.txt in scripts folder.

**Comment by cairthenn** [comment]
I pushed a rebuilt version to -dev that seems to address this.

**Comment by Iminiillusions** [comment]
cool. thanks Cair!

**Comment by Iminiillusions** [comment]
can probably close for now, will reopen if the issue persists
