### ISSUE TITLE
POL Crash at splash screen with windower

### ISSUE THREAD

**Issue by notnate75** [Windower/Issues#995]
When I try to open POL launcher from windower i get the POL splash screen and then it hangs.  Within 5 seconds it shows in the task manager as "not responding".  I have seen a few other posts for similar issues over the last couple months that are still open and no solution posted, so i thought i would toss mine in too.  I am a returning player, new install on windows 10 PC.  I have tried with and without compatibility mode.  Playonline and ffxi run fine without windower (aside from getting them to work with my xbox controllers...)  

Edit: I have a .dmp file for you, but i see no way to upload it

**Comment by notnate75** [comment]
Closed with no comment?   Did I break some rule? Is there a fix that I'm missing?

**Comment by z16** [comment]
Sorry, I wrote the comment, but apparently it didn't post it automatically when I closed the issue... I thought I remembered it doing that.

You mentioned yourself there are other issues open, there is no need for duplicates. If you believe you're experiencing a different issue, let us know why. Otherwise you can just comment on the other thread with any new information you have.

As for the dump, you can upload it to any file hoster or use a cloud storage option like Dropbox, Google Drive, OneDrive, etc., then just create a link to the file with the respective service.
